name: Swift Format

on:
  push:
    branches:
      - main

concurrency:
  group: format-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: Run swift-format
    runs-on: macos-15  # 或 macos-13/macos-15，视 Xcode 版本需求
    permissions:
      contents: write

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install swift-format
        run: brew install swift-format

      - name: Run swift-format
        run: make format

      - name: Commit and push if needed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format swift code via swift-format"
          branch: ${{ github.head_ref || 'main' }}

